import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          {/* Header */}
          <div className="mb-8 text-center">
            <h1 className="bg-gradient-to-r from-green-500 to-blue-600 bg-clip-text text-4xl font-black text-transparent">
              Privacy Policy
            </h1>
            <p className="mt-4 text-lg text-gray-600">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </div>

          {/* Content */}
          <Card>
            <CardHeader>
              <CardTitle className="text-2xl">Introduction</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <p className="text-gray-700">
                At FlowQL, we are committed to protecting your privacy and
                personal information. This Privacy Policy explains how we
                collect, use, disclose, and safeguard your information when you
                use our website and services.
              </p>

              <p className="text-gray-700">
                By using FlowQL, you consent to the data practices described in
                this Privacy Policy. If you do not agree with our practices,
                please do not use our services.
              </p>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">Information We Collect</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Personal Information
                </h3>
                <p className="mb-2 text-gray-700">
                  We collect information you provide directly to us, including:
                </p>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>Email address when you create an account</li>
                  <li>Name and profile information (if provided)</li>
                  <li>
                    Authentication information from OAuth providers (Google,
                    GitHub)
                  </li>
                  <li>Communication preferences and settings</li>
                </ul>
              </div>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Website Analysis Data
                </h3>
                <p className="mb-2 text-gray-700">
                  When you use our analysis services, we process:
                </p>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>Website URLs you submit for analysis</li>
                  <li>Publicly available website content and metadata</li>
                  <li>Analysis results and reports generated by our systems</li>
                  <li>Usage patterns and service interactions</li>
                </ul>
              </div>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Automatically Collected Information
                </h3>
                <p className="mb-2 text-gray-700">
                  We automatically collect certain information about your device
                  and usage:
                </p>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>IP address and location data</li>
                  <li>Browser type and version</li>
                  <li>Device information and operating system</li>
                  <li>Usage analytics and performance metrics</li>
                  <li>Cookies and similar tracking technologies</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">
                How We Use Your Information
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="mb-4 text-gray-700">
                We use the information we collect to:
              </p>
              <ul className="list-inside list-disc space-y-2 text-gray-700">
                <li>Provide, operate, and maintain our services</li>
                <li>Process website analysis requests and generate reports</li>
                <li>Authenticate users and manage accounts</li>
                <li>Improve our services and develop new features</li>
                <li>
                  Communicate with you about your account and our services
                </li>
                <li>Detect, prevent, and address security issues</li>
                <li>Comply with legal obligations and protect our rights</li>
                <li>Analyze usage patterns to optimize performance</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">
                Information Sharing and Disclosure
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Third-Party Services
                </h3>
                <p className="mb-2 text-gray-700">
                  We may share information with third-party services that help
                  us operate our business:
                </p>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>Authentication providers (Google, GitHub)</li>
                  <li>Cloud hosting and infrastructure services</li>
                  <li>Analytics and monitoring services</li>
                  <li>AI and machine learning services for content analysis</li>
                </ul>
              </div>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Legal Requirements
                </h3>
                <p className="text-gray-700">
                  We may disclose your information if required by law,
                  regulation, or legal process, or if we believe disclosure is
                  necessary to protect our rights, property, or safety, or that
                  of our users or others.
                </p>
              </div>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Business Transfers
                </h3>
                <p className="text-gray-700">
                  If FlowQL is involved in a merger, acquisition, or sale of
                  assets, your information may be transferred as part of that
                  transaction.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">Data Security</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-gray-700">
                We implement appropriate technical and organizational security
                measures to protect your personal information against
                unauthorized access, alteration, disclosure, or destruction.
              </p>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Security Measures
                </h3>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>Encryption of data in transit and at rest</li>
                  <li>Regular security audits and monitoring</li>
                  <li>Access controls and authentication requirements</li>
                  <li>Secure hosting infrastructure</li>
                  <li>Regular security updates and patches</li>
                </ul>
              </div>

              <p className="text-gray-700">
                However, no method of transmission over the internet or
                electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your information, we
                cannot guarantee its absolute security.
              </p>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">Your Privacy Rights</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="mb-4 text-gray-700">
                Depending on your location, you may have certain rights
                regarding your personal information:
              </p>
              <ul className="list-inside list-disc space-y-2 text-gray-700">
                <li>
                  <strong>Access:</strong> Request access to your personal
                  information
                </li>
                <li>
                  <strong>Correction:</strong> Request correction of inaccurate
                  information
                </li>
                <li>
                  <strong>Deletion:</strong> Request deletion of your personal
                  information
                </li>
                <li>
                  <strong>Portability:</strong> Request transfer of your data to
                  another service
                </li>
                <li>
                  <strong>Objection:</strong> Object to processing of your
                  information
                </li>
                <li>
                  <strong>Restriction:</strong> Request restriction of
                  processing
                </li>
              </ul>

              <p className="mt-4 text-gray-700">
                To exercise these rights, please contact us at
                privacy@flowql.com. We will respond to your request within a
                reasonable timeframe and in accordance with applicable laws.
              </p>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">Data Retention</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-gray-700">
                We retain your personal information only for as long as
                necessary to provide our services and fulfill the purposes
                outlined in this Privacy Policy, unless a longer retention
                period is required by law.
              </p>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Retention Periods
                </h3>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>Account information: Until account deletion</li>
                  <li>Website analysis data: 30 days after analysis</li>
                  <li>Usage logs: 90 days</li>
                  <li>Security logs: 1 year</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">Cookies and Tracking</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-gray-700">
                We use cookies and similar tracking technologies to enhance your
                experience and analyze usage patterns. You can control cookie
                settings through your browser preferences.
              </p>

              <div>
                <h3 className="mb-2 text-lg font-semibold text-gray-800">
                  Types of Cookies
                </h3>
                <ul className="list-inside list-disc space-y-1 text-gray-700">
                  <li>Essential cookies for service functionality</li>
                  <li>Performance cookies for analytics</li>
                  <li>Preference cookies for user settings</li>
                  <li>Authentication cookies for account management</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">
                Changes to This Privacy Policy
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-gray-700">
                We may update this Privacy Policy from time to time. We will
                notify you of any material changes by posting the new Privacy
                Policy on this page and updating the &quot;Last updated&quot;
                date.
              </p>

              <p className="text-gray-700">
                We encourage you to review this Privacy Policy periodically for
                any changes. Your continued use of our services after any
                modifications constitutes acceptance of the updated Privacy
                Policy.
              </p>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="text-2xl">Contact Us</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                If you have any questions about this Privacy Policy or our data
                practices, please contact us:
              </p>
              <div className="mt-4 rounded-lg bg-gray-50 p-4">
                <p className="font-semibold text-gray-800">FlowQL</p>
                <p className="text-gray-700">Email: privacy@flowql.com</p>
                <p className="text-gray-700">Website: https://www.flowql.com</p>
                <p className="text-gray-700">Subject: Privacy Policy Inquiry</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
